version: '3.8'

services:
  sinergym:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - sinergym_data:/workspace/data
    env_file:
      - .env
    environment:
    - PYTHONPATH=${PYTHONPATH}:/workspace
    tty: true
    stdin_open: true

volumes:
  sinergym_data:
    driver: local 