# ---------------------------------- BASICS ---------------------------------- #
id: PPO_training
environment: Eplus-radiant_case2_heating-stockholm-continuous-stochastic-v1
episodes: 100

# ------------------------------- SB3 ALGORITHM ------------------------------ #
algorithm:
  name: PPO
  log_interval: 1
  parameters:
    policy: MlpPolicy
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    clip_range_vf: null
    normalize_advantage: true
    ent_coef: 0
    vf_coef: 0.5
    max_grad_norm: 0.5
    use_sde: false
    sde_sample_freq: -1
    rollout_buffer_class: null
    rollout_buffer_kwargs: null
    target_kl: null
    stats_window_size: 100
    tensorboard_log: null
    policy_kwargs: null
    verbose: 1
    seed: null
    device: auto
    _init_setup_model: true

# -------------------------------- EVALUATION -------------------------------- #
evaluation:
  eval_freq: 2
  eval_length: 1

# -------------------------------- ENVIRONMENT ------------------------------- #
env_params:
  seed: null
  reward: LinearReward
# ... other environment parameters

# ---------------------------------- WRAPPER --------------------------------- #
wrappers:
  - NormalizeObservation: {}
  - ExtremeFlowControlWrapper: {}
  - NormalizeAction: {}
  - LoggerWrapper:
      storage_class: sinergym.utils.logger.LoggerStorage
  - CSVLogger: {}
  - WandBLogger:
      entity: davsuacar
      project_name: rl-sinergym
      group: TEST_DEV_CONTAINER
  - ReduceObservationWrapper: 
      obs_reduction: [
        'radiant_hvac_outlet_temperature_living',
        'radiant_hvac_outlet_temperature_kitchen',
        'radiant_hvac_outlet_temperature_bed1',
        'radiant_hvac_outlet_temperature_bed2',
        'radiant_hvac_outlet_temperature_bed3',
        'flow_rate_living',
        'flow_rate_kitchen',
        'flow_rate_bed1',
        'flow_rate_bed2',
        'flow_rate_bed3',
        'heat_source_load_side_heat_transfer_rate',
        'heat_source_load_side_mass_flow_rate',
        'crf',
        'heat_cap_mod',
        'cop_plr_mod',
        'cop_temp_mod',
        'plr_current'
        ]
        



# --------------------------- INITIAL STATE (MODEL) -------------------------- #
# Model from scratch:
model: null

# Local Path:
# model: 
#   local_path: </path/to/model>
# load model normalization if needed
#   normalization:
#     mean: Sinergym_output/evaluation/mean.txt
#     var: Sinergym_output/evaluation/var.txt


# WANDB model path:
# model:
#   project: test-project
#   entity: sail_ugr
#   artifact_name: PPO-Eplus-5zone-hot-continuous-stochastic-v1-episodes-5-id-PPOExperimentExample_2025-02-02_18-31_9jau51uy
#   artifact_type: output
#   artifact_tag: v0
#   artifact_path: Sinergym_output/evaluation/
#   model_path: Sinergym_output/evaluation/best_model.zip
#   # load model normalization if needed
#   normalization:
#     mean: Sinergym_output/evaluation/mean.txt
#     var: Sinergym_output/evaluation/var.txt
